name: Eleventy Build
on:
  push:
    branches:
      - 'main'

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies & build
      # npm build is defined in package.json
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: /_site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
